name: Issue Report / Segnalazione Problema
description: Report an issue encountered on the Minecraft server / Segnala un problema riscontrato nel server Minecraft
title: "[ISSUE] Short description / Breve descrizione"
labels: ["issue"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🇬🇧 English
        Thank you for reporting an issue! Please fill out the form below with as much detail as possible.

        ## 🇮🇹 Italiano
        Grazie per aver segnalato un problema! Compila il modulo seguente con più dettagli possibile.

  - type: dropdown
    id: category
    attributes:
      label: Issue type / Tipo di problema
      options:
        - Technical issue / Problema tecnico
        - Crash / Crash
        - Lag or performance issue / Lag o problema di prestazioni
        - Gameplay issue / Problema di gameplay
        - UI or visual issue (menus, scoreboard, etc.) / Problema grafico o dell'interfaccia (menu, scoreboard, ecc.)
        - Permission issue / Problema di permessi
        - Connection or network issue / Problema di connessione o rete
        - Other / Altro
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary of the issue / Riassunto del problema
      description: |
        🇬🇧 Provide a short summary of the issue.  
        🇮🇹 Fornisci un breve riassunto del problema.
      placeholder: "Short summary / Breve riassunto"
    validations:
      required: true

  - type: textarea
    id: what_were_you_doing
    attributes:
      label: What were you trying to do? / Cosa stavi cercando di fare?
      description: |
        🇬🇧 Explain what you were doing before the issue occurred.  
        🇮🇹 Spiega cosa stavi facendo prima che il problema si verificasse.
      placeholder: |
        Example / Esempio:
        I was trying to open a chest...
    validations:
      required: true

  - type: textarea
    id: what_happened
    attributes:
      label: What happened? / Cosa è successo?
      description: |
        🇬🇧 Describe exactly what happened and why it is a problem.  
        🇮🇹 Descrivi cosa è accaduto esattamente e perché è un problema.
      placeholder: |
        Example / Esempio:
        The chest didn't open and I received an error message...
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior / Comportamento atteso
      description: |
        🇬🇧 Describe what should have happened instead.  
        🇮🇹 Descrivi cosa sarebbe dovuto accadere in condizioni normali.
      placeholder: |
        Example / Esempio:
        The chest should open normally...
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: Steps to reproduce the issue / Passaggi per riprodurre il problema
      description: |
        🇬🇧 List the steps needed to reproduce the issue.  
        🇮🇹 Elenca i passaggi necessari per riprodurre il problema.
      placeholder: |
        1. Go to... / Vai in...
        2. Use the command... / Usa il comando...
        3. Interact with... / Interagisci con...
    validations:
      required: true

  - type: dropdown
    id: reproducibility
    attributes:
      label: Is the issue reproducible? / Il problema è riproducibile?
      options:
        - Always / Sempre
        - Sometimes / A volte
        - Only under specific conditions / Solo in condizioni specifiche
        - I don't know / Non lo so
    validations:
      required: true

  - type: textarea
    id: survival_area
    attributes:
      label: Survival area or context / Area o contesto del Survival
      description: |
        🇬🇧 Specify where in the Survival world the issue occurred (warp, coordinates, region, base, farm, protected area, etc.).  
        🇮🇹 Indica dove si è verificato il problema nel mondo Survival (warp, coordinate, regione, base, farm, area protetta, ecc.).
      placeholder: |
        Example / Esempio:
        - Warp: /warp market
        - Coordinates: X 120, Y 64, Z -340
        - Area: Player base / Base di un giocatore
        - Region: Protected region / Regione protetta
    validations:
      required: true

  - type: input
    id: client_version
    attributes:
      label: Minecraft client version / Versione del client Minecraft
      placeholder: "Example / Esempio: 1.20.4"
    validations:
      required: true

  - type: input
    id: server_version
    attributes:
      label: Server version (if known) / Versione del server (se conosciuta)
      placeholder: "Example / Esempio: Paper 1.20.4"
    validations:
      required: false

  - type: input
    id: client_mods
    attributes:
      label: Mods or special clients? / Usi mod o client personalizzati?
      placeholder: "Example / Esempio: Lunar Client, Forge, Optifine..."
    validations:
      required: false

  - type: textarea
    id: network_info
    attributes:
      label: Connection details (optional) / Dettagli connessione (opzionale)
      description: |
        🇬🇧 Useful for diagnosing lag or connection issues.  
        🇮🇹 Utile per analizzare problemi di lag o connessione.
      placeholder: |
        Example / Esempio:
        - Ping: 80ms
        - Connection type: Wi‑Fi
        - VPN: No
        - Packet loss: None / Nessuna perdita di pacchetti

  - type: textarea
    id: logs
    attributes:
      label: Screenshots or logs (optional) / Screenshot o log (opzionale)
      description: |
        🇬🇧 Paste any relevant logs or attach screenshots after submitting.  
        🇮🇹 Incolla eventuali log rilevanti o allega screenshot dopo l’invio.
      placeholder: "Paste logs here / Incolla i log qui"

  - type: dropdown
    id: severity
    attributes:
      label: Severity / Gravità
      options:
        - Critical (game-breaking) / Critico (blocca il gioco)
        - High (major issue) / Alto (problema importante)
        - Medium (annoying but playable) / Medio (fastidioso ma giocabile)
        - Minor (visual or harmless issue) / Minore (problema estetico o poco rilevante)
    validations:
      required: true

  - type: textarea
    id: additional_info
    attributes:
      label: Additional information / Informazioni aggiuntive
      description: |
        🇬🇧 Add anything else that might help us understand the issue.  
        🇮🇹 Aggiungi qualsiasi altra informazione utile alla comprensione del problema.
      placeholder: "Optional notes / Note opzionali"
